### ISSUE TITLE
standardize program names

### ISSUE THREAD

**Issue by Swanson-Hysell** [ltauxe/PmagPy#26]
Going through the manuscript, I realized that, at present, Make_magic.py and QuickMagIC.py have similar names but with different syntax in terms of capitalization and the underscore. It seems like these should be standardized. 

Also, is QuickMagIC still the right name for that program? As an executable, this program now accomplishes a lot in terms of data import, data wrangling, PCA fits through demag_gui, and paleointensity data reduction through thellier_gui. I'm not sure what a better name would be. Perhaps if MagIC.py is going to be retired, QuickMagIC could be renamed MagIC.py?

**Comment by moonshoes87** [comment]
QuickMagIC was named by Ron Shaar, and it did a bit less at that point.  I named "make_magic.py" because I thought it was irritating to have to type 4 upper-case letters to invoke the program.

Pep8 style conventions here: https://www.python.org/dev/peps/pep-0008/#package-and-module-names.  I've been referring to the program overall as MakeMagIC and the Python module as make_magic.py, but perhaps this is more confusing than helpful.  

 I think renaming QuickMagIC to MagIC makes sense if it is the main PmagPy GUI.

**Comment by Swanson-Hysell** [comment]
Lori and Lisa figured out a solution along the lines of:

QuickMagIC =>  Pmag GUI = pmag_gui.py
Make_magic => MakeMagIC GUI = make_magic_gui.py
Thellier GUI = thellier_gui.py
Demag GUI = demag_gui.py
